/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Server */

#ifndef _Included_Server
#define _Included_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Server
 * Method:    cLaunchMethod
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Server_cLaunchMethod
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
